"""baseline_schema

Revision ID: 8295ca9dc780
Revises:
Create Date: 2026-06-01 19:06:25.447510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8295ca9dc780"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classifier_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chamada_em", sa.DateTime(), nullable=False),
        sa.Column("modelo", sa.String(), nullable=False),
        sa.Column("prompt_versao", sa.String(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("confianca", sa.Float(), nullable=True),
        sa.Column("escalado", sa.Boolean(), nullable=False),
        sa.Column("motivo_escalada", sa.String(), nullable=True),
        sa.Column("custo_usd", sa.Float(), nullable=True),
        sa.Column("latencia_ms", sa.Integer(), nullable=True),
        sa.Column("texto_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_classifier_metrics_chamada_em", "classifier_metrics", ["chamada_em"], unique=False
    )
    op.create_index(
        "idx_classifier_metrics_escalado", "classifier_metrics", ["escalado"], unique=False
    )
    op.create_index("idx_classifier_metrics_modelo", "classifier_metrics", ["modelo"], unique=False)
    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("razao_social", sa.String(), nullable=True),
        sa.Column("cnpj", sa.String(), nullable=True),
        sa.Column("setor", sa.String(), nullable=True),
        sa.Column("site", sa.String(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("branding_json", sa.Text(), nullable=True),
        sa.Column("criada_em", sa.DateTime(), nullable=False),
        sa.Column("atualizada_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj"),
        sa.UniqueConstraint("nome"),
    )
    op.create_index("idx_empresas_nome", "empresas", ["nome"], unique=False)
    op.create_table(
        "eventos_manutencao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("qtd_afetada", sa.Integer(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("mensagem", sa.Text(), nullable=True),
        sa.Column("executado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_eventos_manut_em", "eventos_manutencao", ["executado_em"], unique=False)
    op.create_index("idx_eventos_manut_tipo", "eventos_manutencao", ["tipo"], unique=False)
    op.create_table(
        "glossario_termo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("termo", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("definicao_curta", sa.Text(), nullable=False),
        sa.Column("definicao_completa", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(), nullable=True),
        sa.Column("onde_aparece", sa.Text(), nullable=True),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "idx_glossario_categoria", "glossario_termo", ["categoria", "ordem"], unique=False
    )
    op.create_table(
        "acoes_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("item_chave", sa.String(), nullable=False),
        sa.Column("perspectiva", sa.String(), nullable=True),
        sa.Column("perspectiva_confianca", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("responsavel", sa.String(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "item_chave"),
    )
    op.create_index("ix_acoes_status_empresa", "acoes_status", ["empresa_id"], unique=False)
    op.create_table(
        "agrupamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("criterio_json", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.CheckConstraint("tipo IN ('lista','criterio')", name="ck_agrupamentos_tipo"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nome"),
    )
    op.create_table(
        "chat_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("escopo_hash", sa.String(), nullable=False),
        sa.Column("pergunta_hash", sa.String(), nullable=False),
        sa.Column("pergunta", sa.Text(), nullable=False),
        sa.Column("resposta", sa.Text(), nullable=False),
        sa.Column("contexto_hash", sa.String(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_cache_chave",
        "chat_cache",
        ["empresa_id", "escopo_hash", "pergunta_hash"],
        unique=True,
    )
    op.create_index(
        "ix_chat_cache_empresa", "chat_cache", ["empresa_id", "criado_em"], unique=False
    )
    op.create_table(
        "cruzamentos_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("periodo", sa.String(), nullable=False),
        sa.Column("tema_label", sa.String(), nullable=False),
        sa.Column("tema_slug", sa.String(), nullable=False),
        sa.Column("membros_json", sa.Text(), nullable=True),
        sa.Column("buckets_envolvidos_json", sa.Text(), nullable=True),
        sa.Column("tipos_envolvidos_json", sa.Text(), nullable=True),
        sa.Column("n_subpilares_distintos", sa.Integer(), nullable=True),
        sa.Column("peso", sa.Float(), nullable=False),
        sa.Column("eh_semantico", sa.Boolean(), nullable=False),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cruz_snap",
        "cruzamentos_snapshot",
        ["empresa_id", "periodo", "tema_slug"],
        unique=False,
    )
    op.create_table(
        "fontes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("entidade_tipo", sa.String(), nullable=False),
        sa.Column("entidade_id", sa.Integer(), nullable=False),
        sa.Column("conector_tipo", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("autenticacao_tipo", sa.String(), nullable=True),
        sa.Column("credenciais_cifradas", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("ultima_coleta", sa.DateTime(), nullable=True),
        sa.Column("criada_em", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "autenticacao_tipo IN ('publica','autenticada')", name="ck_fontes_autenticacao_tipo"
        ),
        sa.CheckConstraint("entidade_tipo IN ('local','empresa')", name="ck_fontes_entidade_tipo"),
        sa.CheckConstraint("status IN ('ativa','pausada','erro')", name="ck_fontes_status"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_fontes_ativo", "fontes", ["ativo"], unique=False)
    op.create_index("idx_fontes_empresa", "fontes", ["empresa_id"], unique=False)
    op.create_index("idx_fontes_entidade", "fontes", ["entidade_tipo", "entidade_id"], unique=False)
    op.create_table(
        "gini_concentracao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("escopo_tipo", sa.String(), nullable=False),
        sa.Column("escopo_id", sa.Integer(), nullable=True),
        sa.Column("gini", sa.Float(), nullable=True),
        sa.Column("top_n_lojas", sa.Integer(), nullable=True),
        sa.Column("distribuicao_json", sa.Text(), nullable=True),
        sa.Column("calculado_em", sa.DateTime(), nullable=False),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gini_escopo",
        "gini_concentracao",
        ["empresa_id", "escopo_tipo", "escopo_id"],
        unique=False,
    )
    op.create_table(
        "previsibilidade_calculations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("escopo_tipo", sa.String(), nullable=False),
        sa.Column("escopo_id", sa.Integer(), nullable=True),
        sa.Column("previsibilidade_0_100", sa.Float(), nullable=True),
        sa.Column("faixa", sa.String(), nullable=True),
        sa.Column("n_meses", sa.Integer(), nullable=True),
        sa.Column("cv", sa.Float(), nullable=True),
        sa.Column("calculado_em", sa.DateTime(), nullable=False),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_previsib_escopo",
        "previsibilidade_calculations",
        ["empresa_id", "escopo_tipo", "escopo_id"],
        unique=False,
    )
    op.create_table(
        "proximity_calculations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("escopo_tipo", sa.String(), nullable=False),
        sa.Column("escopo_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=True),
        sa.Column("pilar", sa.String(), nullable=True),
        sa.Column("proximity_0_100", sa.Float(), nullable=True),
        sa.Column("faixa", sa.String(), nullable=True),
        sa.Column("calculado_em", sa.DateTime(), nullable=False),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.CheckConstraint(
            "NOT (subpilar IS NOT NULL AND pilar IS NOT NULL)", name="ck_proximity_grao"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_proximity_escopo",
        "proximity_calculations",
        ["empresa_id", "escopo_tipo", "escopo_id"],
        unique=False,
    )
    op.create_table(
        "relatorio_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("escopo_hash", sa.String(), nullable=False),
        sa.Column("secao", sa.String(), nullable=False),
        sa.Column("conteudo_json", sa.Text(), nullable=False),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "escopo_hash", "secao"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("senha_hash", sa.String(), nullable=False),
        sa.Column("papel", sa.String(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=True),
        sa.Column("escopo_json", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("ultimo_login", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "papel IN ('admin_loyall','cliente_total','cliente_restrito')", name="ck_usuarios_papel"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_usuarios_empresa", "usuarios", ["empresa_id"], unique=False)
    op.create_table(
        "coletas_execucoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("fonte_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("iniciado_em", sa.DateTime(), nullable=False),
        sa.Column("concluido_em", sa.DateTime(), nullable=True),
        sa.Column("coletados", sa.Integer(), nullable=False),
        sa.Column("novos", sa.Integer(), nullable=False),
        sa.Column("duplicados", sa.Integer(), nullable=False),
        sa.Column("erros", sa.Integer(), nullable=False),
        sa.Column("mensagem_erro", sa.Text(), nullable=True),
        sa.Column("custo_apify_centavos", sa.Integer(), nullable=True),
        sa.CheckConstraint("status IN ('rodando','concluido','erro')", name="ck_coletas_status"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fonte_id"], ["fontes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_coletas_empresa", "coletas_execucoes", ["empresa_id"], unique=False)
    op.create_index("idx_coletas_fonte", "coletas_execucoes", ["fonte_id"], unique=False)
    op.create_index("idx_coletas_iniciado", "coletas_execucoes", ["iniciado_em"], unique=False)
    op.create_index("idx_coletas_status", "coletas_execucoes", ["status"], unique=False)
    op.create_table(
        "locais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("endereco", sa.String(), nullable=True),
        sa.Column("cidade", sa.String(), nullable=True),
        sa.Column("uf", sa.String(), nullable=True),
        sa.Column("pais", sa.String(), nullable=True),
        sa.Column("place_id_google", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("data_inicio_operacao", sa.Date(), nullable=True),
        sa.Column("observacao", sa.String(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ativo','em_obra','desativado','encerrado')", name="ck_locais_status"
        ),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_locais_agrupamento", "locais", ["agrupamento_id"], unique=False)
    op.create_index("idx_locais_empresa", "locais", ["empresa_id"], unique=False)
    op.create_index("idx_locais_place", "locais", ["place_id_google"], unique=False)
    op.create_table(
        "temas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["criado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "slug", name="uq_temas_empresa_slug"),
    )
    op.create_index("idx_temas_empresa_ativo", "temas", ["empresa_id", "ativo"], unique=False)
    op.create_table(
        "temas_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("tema_label", sa.String(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("percentual", sa.Float(), nullable=False),
        sa.Column("tendencia_pct", sa.Float(), nullable=True),
        sa.Column("periodo_inicio", sa.Date(), nullable=False),
        sa.Column("periodo_fim", sa.Date(), nullable=False),
        sa.Column("exemplos_verbatim_ids", sa.Text(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.Column("hash_escopo", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_temas_bucket", "temas_cache", ["empresa_id", "subpilar", "tipo"], unique=False
    )
    op.create_index("idx_temas_empresa", "temas_cache", ["empresa_id"], unique=False)
    op.create_index("idx_temas_escopo", "temas_cache", ["hash_escopo"], unique=False)
    op.create_table(
        "temas_cruzamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("tema_label", sa.String(), nullable=False),
        sa.Column("buckets_envolvidos_json", sa.Text(), nullable=False),
        sa.Column("tipos_envolvidos_json", sa.Text(), nullable=True),
        sa.Column("membros_json", sa.Text(), nullable=True),
        sa.Column("n_subpilares_distintos", sa.Integer(), nullable=True),
        sa.Column("peso", sa.Float(), nullable=False),
        sa.Column("periodo_inicio", sa.Date(), nullable=False),
        sa.Column("periodo_fim", sa.Date(), nullable=False),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.Column("hash_escopo", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_cruz_empresa", "temas_cruzamentos", ["empresa_id"], unique=False)
    op.create_table(
        "temas_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("periodo", sa.String(), nullable=False),
        sa.Column("tema_slug", sa.String(), nullable=False),
        sa.Column("tema_label", sa.String(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("promotor", sa.Integer(), nullable=False),
        sa.Column("conversivel", sa.Integer(), nullable=False),
        sa.Column("detrator", sa.Integer(), nullable=False),
        sa.Column("centroide", sa.LargeBinary(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_temas_snap", "temas_snapshot", ["empresa_id", "periodo", "tema_slug"], unique=False
    )
    op.create_table(
        "acoes_venda",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("tema_label", sa.String(), nullable=False),
        sa.Column("cruzamento_id", sa.Integer(), nullable=True),
        sa.Column("acao_texto", sa.Text(), nullable=False),
        sa.Column("impacto_qualitativo", sa.String(), nullable=False),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("pressupostos_json", sa.Text(), nullable=True),
        sa.Column("impacto_quant_json", sa.Text(), nullable=True),
        sa.Column("origem_modelo", sa.String(), nullable=True),
        sa.Column("custo_usd", sa.Float(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.Column("hash_escopo", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cruzamento_id"], ["temas_cruzamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_acoes_cruzamento", "acoes_venda", ["cruzamento_id"], unique=False)
    op.create_index("idx_acoes_empresa", "acoes_venda", ["empresa_id"], unique=False)
    op.create_table(
        "anomalias_detectadas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=True),
        sa.Column("tema_id", sa.Integer(), nullable=True),
        sa.Column("cruzamento_id", sa.Integer(), nullable=True),
        sa.Column("chave", sa.String(), nullable=True),
        sa.Column("score_temporal", sa.Float(), nullable=True),
        sa.Column("score_cross_sectional", sa.Float(), nullable=True),
        sa.Column("score_final", sa.Float(), nullable=True),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("direcao", sa.String(), nullable=True),
        sa.Column("tendencia", sa.String(), nullable=True),
        sa.Column("severidade", sa.String(), nullable=True),
        sa.Column("leitura_editorial", sa.Text(), nullable=True),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.Column("recomendacoes_json", sa.Text(), nullable=True),
        sa.Column("periodo", sa.String(), nullable=True),
        sa.Column("detectada_em", sa.DateTime(), nullable=False),
        sa.Column("revisada", sa.Boolean(), nullable=False),
        sa.Column("revisada_por", sa.Integer(), nullable=True),
        sa.Column("revisada_em", sa.DateTime(), nullable=True),
        sa.Column("estado_validacao", sa.String(), nullable=True),
        sa.Column("nota_editorial", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cruzamento_id"], ["temas_cruzamentos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revisada_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tema_id"], ["temas.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_anomalias_cruzamento", "anomalias_detectadas", ["cruzamento_id"], unique=False
    )
    op.create_index("idx_anomalias_empresa", "anomalias_detectadas", ["empresa_id"], unique=False)
    op.create_index("idx_anomalias_sev", "anomalias_detectadas", ["severidade"], unique=False)
    op.create_index("idx_anomalias_tema", "anomalias_detectadas", ["tema_id"], unique=False)
    op.create_index("idx_anomalias_tipo", "anomalias_detectadas", ["tipo"], unique=False)
    op.create_table(
        "leituras_diagnostico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=False),
        sa.Column("leitura", sa.Text(), nullable=False),
        sa.Column("acao", sa.Text(), nullable=True),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_diag_escopo_loja",
        "leituras_diagnostico",
        ["empresa_id", "agrupamento_id", "local_id", "subpilar"],
        unique=False,
    )
    op.create_index(
        "ix_leituras_diag_escopo",
        "leituras_diagnostico",
        ["empresa_id", "agrupamento_id", "subpilar"],
        unique=False,
    )
    op.create_table(
        "locais_metadados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_id", sa.Integer(), nullable=False),
        sa.Column("chave", sa.String(), nullable=False),
        sa.Column("valor", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local_id", "chave"),
    )
    op.create_index("idx_metadados_chave", "locais_metadados", ["chave"], unique=False)
    op.create_index("idx_metadados_local", "locais_metadados", ["local_id"], unique=False)
    op.create_table(
        "ratios_mensais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=False),
        sa.Column("periodo", sa.String(), nullable=False),
        sa.Column("promotor", sa.Integer(), nullable=False),
        sa.Column("conversivel", sa.Integer(), nullable=False),
        sa.Column("detrator", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ratios_mensais", "ratios_mensais", ["empresa_id", "subpilar", "periodo"], unique=False
    )
    op.create_index(
        "idx_ratios_mensais_local",
        "ratios_mensais",
        ["local_id", "subpilar", "periodo"],
        unique=False,
    )
    op.create_table(
        "sugestoes_estruturais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("agrupamento_id", sa.Integer(), nullable=True),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=False),
        sa.Column("perspectiva", sa.String(), nullable=False),
        sa.Column("acao", sa.Text(), nullable=False),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("dados_hash", sa.String(), nullable=True),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agrupamento_id"], ["agrupamentos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sugest_escopo_loja",
        "sugestoes_estruturais",
        ["empresa_id", "agrupamento_id", "local_id", "subpilar"],
        unique=False,
    )
    op.create_index(
        "ix_sugest_estrut_escopo",
        "sugestoes_estruturais",
        ["empresa_id", "agrupamento_id", "subpilar"],
        unique=False,
    )
    op.create_table(
        "temas_merges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tema_origem_id", sa.Integer(), nullable=False),
        sa.Column("tema_destino_id", sa.Integer(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("executado_em", sa.DateTime(), nullable=False),
        sa.Column("executado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["executado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tema_destino_id"], ["temas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tema_origem_id"], ["temas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_temas_merges_destino", "temas_merges", ["tema_destino_id"], unique=False)
    op.create_index("idx_temas_merges_origem", "temas_merges", ["tema_origem_id"], unique=False)
    op.create_table(
        "verbatins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("fonte_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("autor", sa.String(), nullable=True),
        sa.Column("data_criacao_original", sa.DateTime(), nullable=True),
        sa.Column("data_coleta", sa.DateTime(), nullable=False),
        sa.Column("hash_dedup", sa.String(), nullable=True),
        sa.Column("subpilar", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("confianca", sa.Float(), nullable=True),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("prompt_versao", sa.String(), nullable=True),
        sa.Column("tem_texto", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("review_id_externo", sa.String(), nullable=True),
        sa.Column("reclassificado_em", sa.DateTime(), nullable=True),
        sa.Column("reclassificado_por", sa.Integer(), nullable=True),
        sa.Column("subpilar_anterior", sa.String(), nullable=True),
        sa.Column("tipo_anterior", sa.String(), nullable=True),
        sa.Column("local_anterior", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "subpilar IN ('P1','P2','P3','D1','D2','D3','Pa1','Pa2','Pa3','A1','A2','A3','sem_lastro')",
            name="ck_verbatins_subpilar",
        ),
        sa.CheckConstraint(
            "tipo IN ('promotor','conversivel','detrator','inativo')", name="ck_verbatins_tipo"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fonte_id"], ["fontes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["local_id"], ["locais.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reclassificado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "hash_dedup"),
    )
    op.create_index("idx_verbatins_classif", "verbatins", ["subpilar", "tipo"], unique=False)
    op.create_index("idx_verbatins_data", "verbatins", ["data_criacao_original"], unique=False)
    op.create_index("idx_verbatins_empresa", "verbatins", ["empresa_id"], unique=False)
    op.create_index("idx_verbatins_fonte", "verbatins", ["fonte_id"], unique=False)
    op.create_index("idx_verbatins_local", "verbatins", ["local_id"], unique=False)
    op.create_index(
        "idx_verbatins_review_ext",
        "verbatins",
        ["fonte_id", "review_id_externo"],
        unique=True,
        sqlite_where=sa.text("review_id_externo IS NOT NULL"),
        postgresql_where=sa.text("review_id_externo IS NOT NULL"),
    )
    op.create_table(
        "verbatim_embeddings",
        sa.Column("verbatim_id", sa.Integer(), nullable=False),
        sa.Column("modelo", sa.String(), nullable=False),
        sa.Column("vetor", sa.LargeBinary(), nullable=False),
        sa.Column("gerado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["verbatim_id"], ["verbatins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("verbatim_id", "modelo"),
    )
    op.create_index(
        "idx_verbatim_embeddings_modelo", "verbatim_embeddings", ["modelo"], unique=False
    )
    op.create_table(
        "verbatim_temas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("verbatim_id", sa.Integer(), nullable=False),
        sa.Column("tema_id", sa.Integer(), nullable=False),
        sa.Column("confianca", sa.Float(), nullable=False),
        sa.Column("origem", sa.String(), nullable=False),
        sa.Column("evidencia_curta", sa.Text(), nullable=True),
        sa.Column("bucket_chave", sa.String(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.CheckConstraint("origem IN ('llm','manual','merge')", name="ck_verbatim_temas_origem"),
        sa.CheckConstraint(
            "confianca >= 0.0 AND confianca <= 1.0", name="ck_verbatim_temas_confianca"
        ),
        sa.ForeignKeyConstraint(["tema_id"], ["temas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verbatim_id"], ["verbatins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("verbatim_id", "tema_id", name="uq_verbatim_temas_par"),
    )
    op.create_index("idx_verbatim_temas_bucket", "verbatim_temas", ["bucket_chave"], unique=False)
    op.create_index("idx_verbatim_temas_tema", "verbatim_temas", ["tema_id"], unique=False)
    op.create_index("idx_verbatim_temas_verbatim", "verbatim_temas", ["verbatim_id"], unique=False)
    op.create_table(
        "verbatins_reclassificacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("verbatim_id", sa.Integer(), nullable=False),
        sa.Column("subpilar_anterior", sa.String(), nullable=True),
        sa.Column("tipo_anterior", sa.String(), nullable=True),
        sa.Column("subpilar_novo", sa.String(), nullable=False),
        sa.Column("tipo_novo", sa.String(), nullable=False),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("reclassificado_por", sa.Integer(), nullable=True),
        sa.Column("reclassificado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["reclassificado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verbatim_id"], ["verbatins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_recl_em", "verbatins_reclassificacoes", ["reclassificado_em"], unique=False
    )
    op.create_index(
        "idx_recl_verbatim", "verbatins_reclassificacoes", ["verbatim_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_recl_verbatim", table_name="verbatins_reclassificacoes")
    op.drop_index("idx_recl_em", table_name="verbatins_reclassificacoes")
    op.drop_table("verbatins_reclassificacoes")
    op.drop_index("idx_verbatim_temas_verbatim", table_name="verbatim_temas")
    op.drop_index("idx_verbatim_temas_tema", table_name="verbatim_temas")
    op.drop_index("idx_verbatim_temas_bucket", table_name="verbatim_temas")
    op.drop_table("verbatim_temas")
    op.drop_index("idx_verbatim_embeddings_modelo", table_name="verbatim_embeddings")
    op.drop_table("verbatim_embeddings")
    op.drop_index(
        "idx_verbatins_review_ext",
        table_name="verbatins",
        sqlite_where=sa.text("review_id_externo IS NOT NULL"),
        postgresql_where=sa.text("review_id_externo IS NOT NULL"),
    )
    op.drop_index("idx_verbatins_local", table_name="verbatins")
    op.drop_index("idx_verbatins_fonte", table_name="verbatins")
    op.drop_index("idx_verbatins_empresa", table_name="verbatins")
    op.drop_index("idx_verbatins_data", table_name="verbatins")
    op.drop_index("idx_verbatins_classif", table_name="verbatins")
    op.drop_table("verbatins")
    op.drop_index("idx_temas_merges_origem", table_name="temas_merges")
    op.drop_index("idx_temas_merges_destino", table_name="temas_merges")
    op.drop_table("temas_merges")
    op.drop_index("ix_sugest_estrut_escopo", table_name="sugestoes_estruturais")
    op.drop_index("ix_sugest_escopo_loja", table_name="sugestoes_estruturais")
    op.drop_table("sugestoes_estruturais")
    op.drop_index("idx_ratios_mensais_local", table_name="ratios_mensais")
    op.drop_index("idx_ratios_mensais", table_name="ratios_mensais")
    op.drop_table("ratios_mensais")
    op.drop_index("idx_metadados_local", table_name="locais_metadados")
    op.drop_index("idx_metadados_chave", table_name="locais_metadados")
    op.drop_table("locais_metadados")
    op.drop_index("ix_leituras_diag_escopo", table_name="leituras_diagnostico")
    op.drop_index("ix_diag_escopo_loja", table_name="leituras_diagnostico")
    op.drop_table("leituras_diagnostico")
    op.drop_index("idx_anomalias_tipo", table_name="anomalias_detectadas")
    op.drop_index("idx_anomalias_tema", table_name="anomalias_detectadas")
    op.drop_index("idx_anomalias_sev", table_name="anomalias_detectadas")
    op.drop_index("idx_anomalias_empresa", table_name="anomalias_detectadas")
    op.drop_index("idx_anomalias_cruzamento", table_name="anomalias_detectadas")
    op.drop_table("anomalias_detectadas")
    op.drop_index("idx_acoes_empresa", table_name="acoes_venda")
    op.drop_index("idx_acoes_cruzamento", table_name="acoes_venda")
    op.drop_table("acoes_venda")
    op.drop_index("idx_temas_snap", table_name="temas_snapshot")
    op.drop_table("temas_snapshot")
    op.drop_index("idx_cruz_empresa", table_name="temas_cruzamentos")
    op.drop_table("temas_cruzamentos")
    op.drop_index("idx_temas_escopo", table_name="temas_cache")
    op.drop_index("idx_temas_empresa", table_name="temas_cache")
    op.drop_index("idx_temas_bucket", table_name="temas_cache")
    op.drop_table("temas_cache")
    op.drop_index("idx_temas_empresa_ativo", table_name="temas")
    op.drop_table("temas")
    op.drop_index("idx_locais_place", table_name="locais")
    op.drop_index("idx_locais_empresa", table_name="locais")
    op.drop_index("idx_locais_agrupamento", table_name="locais")
    op.drop_table("locais")
    op.drop_index("idx_coletas_status", table_name="coletas_execucoes")
    op.drop_index("idx_coletas_iniciado", table_name="coletas_execucoes")
    op.drop_index("idx_coletas_fonte", table_name="coletas_execucoes")
    op.drop_index("idx_coletas_empresa", table_name="coletas_execucoes")
    op.drop_table("coletas_execucoes")
    op.drop_index("idx_usuarios_empresa", table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("relatorio_cache")
    op.drop_index("idx_proximity_escopo", table_name="proximity_calculations")
    op.drop_table("proximity_calculations")
    op.drop_index("idx_previsib_escopo", table_name="previsibilidade_calculations")
    op.drop_table("previsibilidade_calculations")
    op.drop_index("idx_gini_escopo", table_name="gini_concentracao")
    op.drop_table("gini_concentracao")
    op.drop_index("idx_fontes_entidade", table_name="fontes")
    op.drop_index("idx_fontes_empresa", table_name="fontes")
    op.drop_index("idx_fontes_ativo", table_name="fontes")
    op.drop_table("fontes")
    op.drop_index("idx_cruz_snap", table_name="cruzamentos_snapshot")
    op.drop_table("cruzamentos_snapshot")
    op.drop_index("ix_chat_cache_empresa", table_name="chat_cache")
    op.drop_index("ix_chat_cache_chave", table_name="chat_cache")
    op.drop_table("chat_cache")
    op.drop_table("agrupamentos")
    op.drop_index("ix_acoes_status_empresa", table_name="acoes_status")
    op.drop_table("acoes_status")
    op.drop_index("idx_glossario_categoria", table_name="glossario_termo")
    op.drop_table("glossario_termo")
    op.drop_index("idx_eventos_manut_tipo", table_name="eventos_manutencao")
    op.drop_index("idx_eventos_manut_em", table_name="eventos_manutencao")
    op.drop_table("eventos_manutencao")
    op.drop_index("idx_empresas_nome", table_name="empresas")
    op.drop_table("empresas")
    op.drop_index("idx_classifier_metrics_modelo", table_name="classifier_metrics")
    op.drop_index("idx_classifier_metrics_escalado", table_name="classifier_metrics")
    op.drop_index("idx_classifier_metrics_chamada_em", table_name="classifier_metrics")
    op.drop_table("classifier_metrics")
    # ### end Alembic commands ###
